feat: add lab5
s1rserg/voting-system pull request #4
Opened 2024-11-18 09:58 UTC by s1rserg

## *Added Database Setup*
- Installed PostgreSQL as RDBMS
- Created tables using BIGSERIAL for auto-incrementing primary keys
- Added test data for voting system demonstration
- Implemented via migrations using Liquibase

## *Added Core Database Features*
- Implemented sequences for primary key generation using BIGSERIAL
- Created tables:
  - `voting` (main voting information)
  - `candidate` (voting options)
  - `vote` (user votes tracking)
- Added CASCADE deletion for referential integrity

## *Added Repository Layer*
- Created DAO interfaces and implementations for:
  - VotingRepository
  - CandidateRepository
  - VoteRepository
- Implemented CRUD operations
- Added custom search methods:
  - Find all votings (was already implemented)
  - Find votes by voting id and user id
  - Find candidates by voting

## *Added Service Layer*
- Implemented business logic interfaces and classes:
  - VotingService
  - CandidateService
  - VoteService
- Added transactional voting process
- Implemented vote counting and validation

## *Rewrote Controller Layer*
- Added RESTful endpoints:
  - PATCH `/api/votings/{id}/votes` - update a vote
  - DELETE `/api/votings/{id}/votes` - retract a vote

## Entity Relationship Diagram
```mermaid
erDiagram
    voting ||--o{ candidate : "has"
    voting ||--o{ vote : "receives"
    candidate ||--o{ vote : "receives"

    voting {
        bigint id PK
        varchar(255) title
        text description
        boolean active
        bigint creator_user_id
    }

    candidate {
        bigint id PK
        varchar(255) name
        integer votes
        bigint voting_id FK
    }

    vote {
        bigint id PK
        bigint voting_id FK
        bigint candidate_id FK
        bigint user_id
    }
```

2024-11-19 12:41 UTC, HoroshkoMykhailo requested changes

2024-11-19 12:41 UTC, HoroshkoMykhailo commented on src/main/java/com/example/votingsystem/repository/impl/VotingDAOImpl.java
> +        int offset = (page - 1) * size;
page по дефолту 0, воно викликає помилку через те, що offset тоді від'ємний

2024-11-19 12:41 UTC, HoroshkoMykhailo commented on src/main/java/com/example/votingsystem/controller/VotingController.java
>              @RequestParam(defaultValue = "0") int page,
Тут поставити дефолтне значення 1

2024-11-21 12:46 UTC, HoroshkoMykhailo approved these changes

2024-11-21 13:01 UTC, HoroshkoMykhailo requested changes

2024-11-21 13:01 UTC, HoroshkoMykhailo commented on src/main/java/com/example/votingsystem/service/impl/VoteServiceImpl.java
> +        voteDAO.deleteByVotingAndUserId(vote.getId(), userId);
Тут має бути votingId, а не voteId
`voteDAO.deleteByVotingAndUserId(votingId, userId);`

2024-11-21 13:09 UTC, HoroshkoMykhailo requested changes

2024-11-21 13:09 UTC, HoroshkoMykhailo commented on src/main/java/com/example/votingsystem/repository/impl/VotingDAOImpl.java
> +        String sql = "DELETE FROM voting WHERE id = ?";
Ну і тут змінити
```suggestion
        String sql = "DELETE FROM voting WHERE user_id = ?";
```

2024-11-21 13:48 UTC, s1rserg commented on src/main/java/com/example/votingsystem/repository/impl/VotingDAOImpl.java
> +        String sql = "DELETE FROM voting WHERE id = ?";
Тут трохи не зрозумів

2024-11-21 14:09 UTC, HoroshkoMykhailo commented on src/main/java/com/example/votingsystem/repository/impl/VotingDAOImpl.java
> +        String sql = "DELETE FROM voting WHERE id = ?";
не то, ти все правильно зробив

2024-11-21 14:10 UTC, HoroshkoMykhailo approved these changes

2024-11-21 14:10 UTC, HoroshkoMykhailo commented on src/main/java/com/example/votingsystem/repository/impl/VotingDAOImpl.java
> +        String sql = "DELETE FROM voting WHERE id = ?";
Я файли перепутав

2024-11-21 17:52 UTC, merged